#!/usr/bin/env python3

import os
import sys
import glob


class PhoneNumberFormatter:
    def remove_plus_from_number(self, number):
        number = str(number)
        if number.startswith('+79') and len(number) == 12:
            return number[1:]
        if number.startswith('79') and len(number) == 11:
            return number[1:]
        if number.startswith('9') and len(number) == 10:
            return number
        return number

    def process_files(self, files):
        for file in files:
            with open(file, 'r') as f:
                lines = f.readlines()

            updated_lines = []
            for line in lines:
                updated_number = self.remove_plus_from_number(line.strip())
                updated_lines.append(updated_number + '\n')

            with open(file, 'w') as f:
                f.writelines(updated_lines)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: minus <input_file> [input_file2 ...]")
        sys.exit(1)

    input_files = sys.argv[1:]

    formatter = PhoneNumberFormatter()
    files_to_process = []

    for input_file in input_files:
        if "*" in input_file or "?" in input_file:
            matching_files = glob.glob(input_file)
            files_to_process.extend(matching_files)
        else:
            files_to_process.append(input_file)

    try:
        formatter.process_files(files_to_process)
    except Exception as e:
        print(e)
